version: '3.9'

services:
  app:
    build: .
    container_name: image_tagging_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.controller.api_controller:app --host 0.0.0.0 --port 8000 --reload
